### ISSUE TITLE
Node process uses a lot of CPU when in dev mode

### ISSUE THREAD

**Issue by beeman** [swimlane/swui#3]
Nice project, very inspiring as I'm building a set of custom components too :)

On thing I noticed when running it using `npm start` is that there was a node process that never got below 70% CPU usage.

I found that [this line](https://github.com/swimlane/swui/blob/master/config/webpack.dev.js#L17) causes that behavior. The app seemed to keep working when I uncommented it, so I'm not sure if it's needed.

**Comment by amcdnl** [comment]
Thanks for the kind words! I did not realize my CPU spiking, that will def help things out!
